### ISSUE TITLE
Tests fail with JAX 0.11.2

### ISSUE THREAD

**Issue by venkatkapil24** [jax-md/jax-md#423]
On a fresh install, many tests stop before they start. The install uses JAX 0.11.2 and Flax 0.12.9, and reports:

AttributeError: module 'jax.experimental.hijax' has no attribute 'HiPrimitive'

I reproduced this with Python 3.13. Using JAX 0.11.0 instead lets the tests start, and the 12 NPT tests I ran pass.

This explains the test failures in PR #422
